### ISSUE TITLE
Files not included in repository: trajectories2.mat

### ISSUE THREAD

**Issue by Walshest** [mathworks/Simulation-Animation-Deployment-for-Simulink-Compiler#1]
Hi, 
I have issues when clicking the start button on the app. It is missing files which fail to be loaded: 
`                    switch app.DropDown.Value
                        case 1
                            t=load("trajectories2.mat","t1");
                            traj=t.t1;
                        case 2
                            t=load("trajectories2.mat","t2");
                            traj=t.t2;
                        case 3
                            t=load("trajectories2.mat","t3");
                            traj=t.t3;
                    end`
I assume these files are the same as the same file: trajectories.mat which is included?

**Comment by ghost** [comment]
Hi Stefan:

Thanks for reporting this issue. I've added the missing trajectories2.mat file needed by this example. Let us know if you run into any additional issues.

Best Regards
Murali

**Comment by ghost** [comment]
resolved.
